-- Search Keywords Analysis Extended Data
-- 搜索关键词分析表扩展数据

INSERT INTO search_keywords (keyword, search_volume, cpc, platform, category, search_intent, trend, notes)
VALUES 
-- Existing data
('eufy vacuum and mop', 880, NULL, 'Google', '产品特性', '购买意向', '上升', '显示消费者对多功能设备的需求'),
('eufy vacuum robot', 720, NULL, 'Google', '产品类型', '购买意向', '稳定', '反映对自动化解决方案的需求'),
('eufy vacuum red light', 480, NULL, 'Google', '问题解决', '技术支持', '上升', '最常见的技术问题'),
('best eufy vacuum', 590, NULL, 'Google', '比较', '研究', '稳定', '购买前研究行为'),
('eufy vacuum deals', 390, 0.00, 'Google', '价格', '促销', '波动', '高价格敏感性'),

-- New extended data
('eufy robovac x8', 850, 1.25, 'Google', '产品型号', '购买意向', '上升', '特定型号搜索表明强烈购买意向'),
('eufy vs roomba', 780, 1.85, 'Google', '比较', '研究', '稳定', '与主要竞争对手的比较搜索'),
('eufy robovac battery replacement', 520, 0.95, 'Google', '维护', '技术支持', '上升', '常见维护需求'),
('eufy robovac not charging', 470, NULL, 'Google', '问题解决', '技术支持', '上升', '常见充电问题'),
('eufy robovac wifi connection', 430, NULL, 'Google', '问题解决', '技术支持', '稳定', '连接问题搜索'),
('eufy robovac filter replacement', 410, 0.75, 'Google', '维护', '购买意向', '稳定', '耗材更换需求'),
('eufy robovac side brush', 380, 0.65, 'Google', '维护', '购买意向', '稳定', '配件更换搜索'),
('eufy robovac app not working', 360, NULL, 'Google', '问题解决', '技术支持', '上升', 'APP问题搜索增加'),
('eufy robovac x8 review', 670, 1.45, 'Google', '评价', '研究', '上升', '购买前详细研究'),
('eufy robovac stuck', 340, NULL, 'Google', '问题解决', '技术支持', '稳定', '常见使用问题'),
('eufy robovac mapping', 420, NULL, 'Google', '功能', '研究', '上升', '智能导航功能搜索'),
('eufy robovac mopping', 560, 1.15, 'Google', '功能', '研究', '上升', '拖地功能搜索增加'),
('eufy robovac pet hair', 630, 1.35, 'Google', '功能', '研究', '上升', '宠物家庭特定需求'),
('eufy robovac noise', 310, NULL, 'Google', '问题', '研究', '稳定', '噪音问题搜索'),
('eufy robovac vs roborock', 540, 1.95, 'Google', '比较', '研究', '上升', '与高端竞争对手比较'),
('eufy robovac battery life', 490, NULL, 'Google', '功能', '研究', '稳定', '电池续航能力搜索'),
('eufy robovac suction power', 520, NULL, 'Google', '功能', '研究', '上升', '清洁能力搜索'),
('eufy robovac carpet', 480, NULL, 'Google', '功能', '研究', '稳定', '地毯清洁能力搜索'),
('eufy robovac error codes', 350, NULL, 'Google', '问题解决', '技术支持', '稳定', '错误代码查询'),
('eufy robovac not turning on', 320, NULL, 'Google', '问题解决', '技术支持', '稳定', '开机问题搜索'),
('eufy robovac amazon', 750, 0.85, 'Google', '购买渠道', '购买意向', '稳定', '特定渠道购买搜索'),
('eufy robovac costco', 580, 0.75, 'Google', '购买渠道', '购买意向', '波动', '促销期间搜索量增加'),
('eufy robovac black friday', 820, 0.95, 'Google', '促销', '购买意向', '季节性', '节日促销搜索'),
('eufy robovac cyber monday', 790, 0.90, 'Google', '促销', '购买意向', '季节性', '节日促销搜索'),
('eufy robovac prime day', 760, 0.85, 'Google', '促销', '购买意向', '季节性', '亚马逊促销日搜索'),
('eufy robovac coupon', 430, 0.65, 'Google', '价格', '购买意向', '波动', '折扣搜索'),
('eufy robovac warranty', 350, NULL, 'Google', '售后', '研究', '稳定', '售后保障搜索'),
('eufy robovac manual', 390, NULL, 'Google', '使用', '技术支持', '稳定', '使用指南搜索'),
('eufy robovac troubleshooting', 420, NULL, 'Google', '问题解决', '技术支持', '稳定', '故障排除搜索'),
('eufy robovac vs dyson', 480, 1.85, 'Google', '比较', '研究', '稳定', '与高端品牌比较'),
('eufy robovac vs shark', 460, 1.75, 'Google', '比较', '研究', '稳定', '与中端品牌比较'),
('eufy robovac vs ilife', 380, 1.45, 'Google', '比较', '研究', '下降', '与低端品牌比较减少'),
('eufy robovac mop attachment', 420, 0.85, 'Google', '配件', '购买意向', '上升', '拖地配件搜索增加'),
('eufy robovac water tank', 380, 0.75, 'Google', '配件', '购买意向', '上升', '水箱配件搜索'),
('eufy robovac filter', 450, 0.65, 'Google', '配件', '购买意向', '稳定', '滤网更换搜索'),
('eufy robovac brush', 430, 0.60, 'Google', '配件', '购买意向', '稳定', '刷子更换搜索'),
('eufy robovac dustbin', 340, 0.55, 'Google', '配件', '购买意向', '稳定', '集尘盒更换搜索'),
('eufy robovac charging dock', 370, 0.85, 'Google', '配件', '购买意向', '稳定', '充电座更换搜索'),
('eufy robovac app download', 420, NULL, 'Google', '使用', '技术支持', '稳定', 'APP下载搜索'),
('eufy robovac setup', 460, NULL, 'Google', '使用', '技术支持', '稳定', '初始设置搜索'),
('eufy robovac wifi setup', 430, NULL, 'Google', '使用', '技术支持', '稳定', 'WiFi连接设置搜索'),
('eufy robovac mapping problem', 350, NULL, 'Google', '问题解决', '技术支持', '上升', '地图问题搜索增加'),
('eufy robovac not connecting to wifi', 380, NULL, 'Google', '问题解决', '技术支持', '上升', 'WiFi连接问题搜索'),
('eufy robovac vs ecovacs', 420, 1.65, 'Google', '比较', '研究', '上升', '与中国品牌比较增加'),
('eufy robovac cleaning schedule', 340, NULL, 'Google', '使用', '技术支持', '稳定', '定时清洁设置搜索'),
('eufy robovac zone cleaning', 380, NULL, 'Google', '功能', '研究', '上升', '区域清洁功能搜索'),
('eufy robovac spot cleaning', 350, NULL, 'Google', '功能', '研究', '稳定', '局部清洁功能搜索'),
('eufy robovac edge cleaning', 330, NULL, 'Google', '功能', '研究', '稳定', '边缘清洁功能搜索'),
('eufy robovac auto empty', 520, 1.25, 'Google', '功能', '研究', '上升', '自动集尘功能搜索增加'),
('eufy robovac lidar', 480, NULL, 'Google', '功能', '研究', '上升', '激光导航技术搜索'),
('eufy robovac obstacle avoidance', 420, NULL, 'Google', '功能', '研究', '上升', '避障功能搜索增加'),
('eufy robovac carpet boost', 390, NULL, 'Google', '功能', '研究', '稳定', '地毯增压功能搜索'),
('eufy robovac battery replacement cost', 350, 0.75, 'Google', '维护', '研究', '上升', '电池更换成本搜索'),
('eufy robovac filter replacement cost', 320, 0.65, 'Google', '维护', '研究', '稳定', '滤网更换成本搜索'),
('eufy robovac side brush replacement', 340, 0.60, 'Google', '维护', '购买意向', '稳定', '边刷更换搜索'),
('eufy robovac roller brush replacement', 360, 0.70, 'Google', '维护', '购买意向', '稳定', '滚刷更换搜索'),
('eufy robovac water tank leaking', 290, NULL, 'Google', '问题解决', '技术支持', '上升', '水箱漏水问题搜索'),
('eufy robovac not picking up dirt', 310, NULL, 'Google', '问题解决', '技术支持', '稳定', '清洁效果问题搜索'),
('eufy robovac making noise', 330, NULL, 'Google', '问题解决', '技术支持', '稳定', '噪音问题搜索'),
('eufy robovac stuck under furniture', 280, NULL, 'Google', '问题解决', '技术支持', '稳定', '卡住问题搜索'),
('eufy robovac bumping into furniture', 290, NULL, 'Google', '问题解决', '技术支持', '稳定', '碰撞问题搜索'),
('eufy robovac not returning to dock', 320, NULL, 'Google', '问题解决', '技术支持', '稳定', '回充问题搜索'),
('eufy robovac vs irobot', 510, 1.95, 'Google', '比较', '研究', '稳定', '与iRobot品牌比较'),
('eufy robovac vs neato', 380, 1.65, 'Google', '比较', '研究', '下降', '与Neato品牌比较减少'),
('eufy robovac vs xiaomi', 420, 1.55, 'Google', '比较', '研究', '上升', '与小米品牌比较增加'),
('eufy robovac vs samsung', 390, 1.75, 'Google', '比较', '研究', '稳定', '与三星品牌比较'),
('eufy robovac vs lg', 370, 1.65, 'Google', '比较', '研究', '稳定', '与LG品牌比较'),
('eufy robovac vs bissell', 350, 1.55, 'Google', '比较', '研究', '稳定', '与Bissell品牌比较'),
('eufy robovac vs hoover', 330, 1.45, 'Google', '比较', '研究', '下降', '与Hoover品牌比较减少'),
('eufy robovac vs electrolux', 310, 1.55, 'Google', '比较', '研究', '稳定', '与伊莱克斯品牌比较'),
('eufy robovac vs philips', 290, 1.45, 'Google', '比较', '研究', '稳定', '与飞利浦品牌比较'),
('eufy robovac vs miele', 270, 1.65, 'Google', '比较', '研究', '稳定', '与美诺品牌比较'),
('eufy robovac vs bosch', 280, 1.55, 'Google', '比较', '研究', '稳定', '与博世品牌比较'),
('eufy robovac vs panasonic', 260, 1.45, 'Google', '比较', '研究', '下降', '与松下品牌比较减少'),
('eufy robovac vs tineco', 290, 1.35, 'Google', '比较', '研究', '上升', '与添可品牌比较增加'),
('eufy robovac vs dreame', 310, 1.45, 'Google', '比较', '研究', '上升', '与追觅品牌比较增加'),
('eufy robovac vs proscenic', 280, 1.35, 'Google', '比较', '研究', '稳定', '与浦桑尼克品牌比较'),
('eufy robovac vs ilife', 270, 1.25, 'Google', '比较', '研究', '下降', '与ILIFE品牌比较减少'),
('eufy robovac vs lefant', 250, 1.15, 'Google', '比较', '研究', '稳定', '与乐帆品牌比较'),
('eufy robovac vs coredy', 240, 1.15, 'Google', '比较', '研究', '稳定', '与科沃斯品牌比较'),
('eufy robovac vs yeedi', 260, 1.25, 'Google', '比较', '研究', '上升', '与易第品牌比较增加'),
('eufy robovac vs kyvol', 230, 1.05, 'Google', '比较', '研究', '下降', '与凯沃品牌比较减少'),
('eufy robovac vs tesvor', 220, 1.05, 'Google', '比较', '研究', '下降', '与特沃斯品牌比较减少'),
('eufy robovac vs amarey', 210, 0.95, 'Google', '比较', '研究', '下降', '与Amarey品牌比较减少'),
('eufy robovac vs bagotte', 200, 0.95, 'Google', '比较', '研究', '下降', '与Bagotte品牌比较减少'),
('eufy robovac vs goovi', 190, 0.85, 'Google', '比较', '研究', '下降', '与GOOVI品牌比较减少'),
('eufy robovac vs dibea', 180, 0.85, 'Google', '比较', '研究', '下降', '与地贝品牌比较减少'),
('eufy robovac vs ikohs', 170, 0.75, 'Google', '比较', '研究', '稳定', '与IKOHS品牌比较'),
('eufy robovac vs cecotec', 160, 0.75, 'Google', '比较', '研究', '稳定', '与Cecotec品牌比较'),
('eufy robovac vs deik', 150, 0.65, 'Google', '比较', '研究', '下降', '与Deik品牌比较减少'),
('eufy robovac vs aposen', 140, 0.65, 'Google', '比较', '研究', '下降', '与Aposen品牌比较减少'),
('eufy robovac vs moosoo', 130, 0.55, 'Google', '比较', '研究', '下降', '与MOOSOO品牌比较减少'),
('eufy robovac vs onson', 120, 0.55, 'Google', '比较', '研究', '下降', '与ONSON品牌比较减少'),
('eufy robovac vs noisz', 110, 0.45, 'Google', '比较', '研究', '下降', '与NOISZ品牌比较减少'),
('eufy robovac vs lubluelu', 100, 0.45, 'Google', '比较', '研究', '下降', '与Lubluelu品牌比较减少');
